
package org.corridor_game.corridor_game.client.generated_proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerManager", targetNamespace = "http://server.corridor_game.corridor_game.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServerManager {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewPlayer", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.AddNewPlayer")
    @ResponseWrapper(localName = "addNewPlayerResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.AddNewPlayerResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/addNewPlayerRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/addNewPlayerResponse")
    public int addNewPlayer();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setReady", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.SetReady")
    @ResponseWrapper(localName = "setReadyResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.SetReadyResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/setReadyRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/setReadyResponse")
    public void setReady(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.corridor_game.corridor_game.client.generated_proxy.FinishGameData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFinishGameData", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.GetFinishGameData")
    @ResponseWrapper(localName = "getFinishGameDataResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.GetFinishGameDataResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/getFinishGameDataRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/getFinishGameDataResponse")
    public FinishGameData getFinishGameData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "paintLine", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.PaintLine")
    @ResponseWrapper(localName = "paintLineResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.PaintLineResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/paintLineRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/paintLineResponse")
    public void paintLine(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        PaintingLine arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.corridor_game.corridor_game.client.generated_proxy.StartGameData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStartGameData", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.GetStartGameData")
    @ResponseWrapper(localName = "getStartGameDataResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.GetStartGameDataResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/getStartGameDataRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/getStartGameDataResponse")
    public StartGameData getStartGameData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.corridor_game.corridor_game.client.generated_proxy.UpdateGameStatusData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGameData", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.UpdateGameData")
    @ResponseWrapper(localName = "updateGameDataResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.UpdateGameDataResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/updateGameDataRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/updateGameDataResponse")
    public List<UpdateGameStatusData> updateGameData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isGameStarted", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.IsGameStarted")
    @ResponseWrapper(localName = "isGameStartedResponse", targetNamespace = "http://server.corridor_game.corridor_game.org/", className = "org.corridor_game.corridor_game.client.generated_proxy.IsGameStartedResponse")
    @Action(input = "http://server.corridor_game.corridor_game.org/ServerManager/isGameStartedRequest", output = "http://server.corridor_game.corridor_game.org/ServerManager/isGameStartedResponse")
    public boolean isGameStarted();

}
