
package org.corridor_game.corridor_game.client.generated_proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerManagerService", targetNamespace = "http://server.corridor_game.corridor_game.org/", wsdlLocation = "http://localhost:5555/GameServer?wsdl")
public class ServerManagerService
    extends Service
{

    private final static URL SERVERMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERMANAGERSERVICE_EXCEPTION;
    private final static QName SERVERMANAGERSERVICE_QNAME = new QName("http://server.corridor_game.corridor_game.org/", "ServerManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5555/GameServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERMANAGERSERVICE_WSDL_LOCATION = url;
        SERVERMANAGERSERVICE_EXCEPTION = e;
    }

    public ServerManagerService() {
        super(__getWsdlLocation(), SERVERMANAGERSERVICE_QNAME);
    }

    public ServerManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERMANAGERSERVICE_QNAME, features);
    }

    public ServerManagerService(URL wsdlLocation) {
        super(wsdlLocation, SERVERMANAGERSERVICE_QNAME);
    }

    public ServerManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERMANAGERSERVICE_QNAME, features);
    }

    public ServerManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerManager
     */
    @WebEndpoint(name = "ServerManagerPort")
    public ServerManager getServerManagerPort() {
        return super.getPort(new QName("http://server.corridor_game.corridor_game.org/", "ServerManagerPort"), ServerManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerManager
     */
    @WebEndpoint(name = "ServerManagerPort")
    public ServerManager getServerManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.corridor_game.corridor_game.org/", "ServerManagerPort"), ServerManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERMANAGERSERVICE_EXCEPTION!= null) {
            throw SERVERMANAGERSERVICE_EXCEPTION;
        }
        return SERVERMANAGERSERVICE_WSDL_LOCATION;
    }

}
